apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: post-run-quality-gate
spec:
  description: >-
    This task runs a quality gate. It can use a Kubeconfig secret to connect to a remote Kubernetes cluster.
  volumes:
    - name: kubeconfig
      secret:
        secretName: $(params.KUBECONFIG_SECRET_NAME)
        optional: true
  params:
    - name: APPLICATIONS_PAYLOAD
      description: |
        Applications payload in format: {"codebase1": {"imageTag": "version1", "customValues": true}, "codebase2": {"imageTag": "version2", "customValues": true}}. For example: {"demo": {"imageTag": "main-20240103-141431", "customValues": true}, "myapp": {"imageTag": "0.1.0-SNAPSHOT.1", "customValues": true}}
      type: string
    - name: PIPELINE
      type: string
      description: |
        EDP kind:CDPipeline name used for deployment. For example: mypipe, myfeature
    - name: STAGE
      description: |
        EDP kind:Stage name of the kind:CDPipeline defined in the CDPIPELINE values. For example: dev, test, prod
      type: string
    - name: BASE_IMAGE
      description: The base image for the task (different for buildtools).
      type: string
      default: ""
    - name: EXTRA_COMMANDS
      type: string
      description: Extra commands
      default: ""
    - name: KUBECONFIG_SECRET_NAME
      type: string
      description: The name of secret with Kubeconfig to connect to the remote cluster
      default: "in-cluster"
  steps:
    - name: run
      image: $(params.BASE_IMAGE)
      volumeMounts:
        - name: kubeconfig
          mountPath: /workspace/source/kube
      envFrom:
        - configMapRef:
            name: $(params.PIPELINE)-$(params.STAGE)
      script: |
        set -ex
        export KUBECONFIG="workspace/source/kube/config"
        $(params.EXTRA_COMMANDS)
